# camera extrinsics
# transformation from camera link to optical link [x y z qw qx qy qz]
# trans_cam_opt: [0.0, 0.0, 0.0, 0.5, -0.5, 0.5, -0.5]
trans_cam_opt: [0.0, 0.0, 0.0, 0, 0, 0, 1]

# transformation from base link to camera link [x y z qw qx qy qz]
# when camera is to the right of the robot (cylinder)
trans_base_cam: [0.2, 0.0, 0.04, 0.0, 0.0, 0.0, 0.0]
# when camera is in the overhead position
# trans_base_cam: [0.500, 0.000, 0.700, 0.707, 0.000, 0.707, 0.000]
