# file path to neural network weights and model config
model_name: "GQCNN-4.0-PJ"
model_dir: "/home/huang/deep_grasp_demo/models/GQCNN-4.0-PJ"
model_params: "/home/huang/deep_grasp_demo/dexnet_deps/gqcnn/cfg/examples/replication/dex-net_4.0_pj.yaml"
